[[redirects]]
  from = "/oxuwiki"
  to = "https://dissonanssi.ayy.fi/oxuwiki"
  status = 301
  force = true

[[redirects]]
  from = "/love"
  to = "https://www.dropbox.com/s/b9g6ada62azle1i/Dissonanssi%20K2023%20k%C3%A4siohjelma%20FINALFINALFINAL.pdf?dl=0"
  status = 302
  force = true
